---
- name: "[Cask] Base packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - iterm2
  - dashlane
  - dropbox
  - magicprefs
  - adobe-creative-cloud
  - visual-studio-code
  - sketch

- name: "[Cask] Extras"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - vlc
  - transmission
  - spotify
  - mac2imgur
  - lastfm
  - freedome

- name: "[Cask] Social"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - slack
  - gitter
  - discord
