---
- name: "[Brew] Update"
  homebrew:
    update_homebrew: yes

# Install core packages
#
# Core packages includes essential tools and support for mostly used programming languages,
# as well as commonly used applications.
- name: "[Brew] Base system install"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - coreutils
  - wget
  - tmux
  - git
  - p7zip
  - unrar

- name: "[Brew] Programming languages"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - elm
  - nvm
  - rbenv
  - leiningen
  - python3
  - haskell-stack

- name: "[Brew] System"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - osquery
  - htop

# Extra packages
#
# Non-essential but useful and/or commonly used applications and programs
- name: "[Brew] Imagemagick with libs"
  homebrew:
    name: imagemagick
    state: latest
    install_options: with-liblqr,with-opencl,with-webp

- name: "[Extras] Tasks"
  include: extras.yml

- name: "[Coding] Tasks"
  include: coding.yml

- name: "[Fonts] Tasks"
  include: fonts.yml
