---
# Install core packages
#
# Core packages includes essential tools and support for mostly used programming languages,
# as well as commonly used applications.
- name: "[Brew] Base system install"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - coreutils
  - wget
  - tmux
  - git

- name: "[Brew] Programming languages"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - elm
  - nvm
  - rbenv
  - leiningen
  - python3

# Extra packages
#
# Non-essential but useful and/or commonly used applications and programs
- name: "[Brew] Imagemagick with libs"
  homebrew:
    name: imagemagick
    state: latest
    install_options: with-liblqr,with-opencl,with-webp

- name: "[Brew] Extras"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
  - youtube-dl

- name: "[Coding] Tasks"
  include: coding.yml
